# Generated by Django 4.1.5 on 2023-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apodo', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ClubFutbol',
        ),
    ]
